namespace DVLD_Presentation
{
    public partial class frmPeopleAddUpdate : Form
    {
        public int _PersonID_Back;
        public frmPeopleAddUpdate(int _PersonID)
        {
            InitializeComponent();
            ctrlPeopleAddUpdate._PersonID = _PersonID;
            ctrlPeopleAddUpdate1.DataBack += Id_DataBack;

            if (_PersonID != -1)
                lblPeopleTitle.Text = "Edit Person Details";
        }

        private void btnPeopleCancel_Click(object sender, EventArgs e)
        {
            this.Close();
        }

        private void frmPeopleAddUpdate_Load(object sender, EventArgs e)
        {
            this.Size = new Size(1570, 1084);
            this.StartPosition = FormStartPosition.Manual;
            this.Location = new Point(Screen.PrimaryScreen.WorkingArea.Width - this.Width, 0);
        }

        private void frmPeopleAddUpdate_FormClosing(object sender, FormClosingEventArgs e)
        {
        }

        private void Id_DataBack(object sender, int PersonID)
        {
            _PersonID_Back = PersonID;


        }

        private void btnDocumentation_Click(object sender, EventArgs e)
        {
            string documentation = "This form allows you to add a new person by filling in all the required fields.\nThe fields for email, third name, and image are optional.\nIf you provide an email, it must be in a valid format.\nThe selected image will be stored in a specific folder with a unique ID name generated by the software.\nUse the Save button to store the person’s information.\nAfter saving, you can still update the data and save again to apply changes.";
            frmDocumentation frmDocumentation = new frmDocumentation(documentation);
            frmDocumentation.ShowDialog();

        }
    }
}
